### ISSUE TITLE
Include Partner Pre-Paid to Renewals Oppty Value

### ISSUE THREAD

**Issue by coreywebber** [coreywebber/bdw#68]
Pat has asked that a value be showed for Partner Pre-Paid deals. Main issue is, it conflicts with the Standard Order Filter.

- [x] Research Partner Pre-Paid Category
- [x] Update Logic to Is_Renewable to include PrePaid, Update Logic to Renewal Value to use Is_Renewable rather then Standard_Order_Flag
- [x] Validate Results on Testing before Deployment
- [x] Update Renewals Report where needed

**Comment by coreywebber** [comment]
After talking to Jason, and he is going to confirm with Pat Gallagher that Pre-Paids are not counted still because the Opportunity is booked and counted under Partner, then child pre-paid accounts are generated under the end user with a split of the main deal at the partner.

**Comment by coreywebber** [comment]
> After talking to Jason, and he is going to confirm with Pat Gallagher that Pre-Paids are not counted still because the Opportunity is booked and counted under Partner, then child pre-paid accounts are generated under the end user with a split of the main deal at the partner.

This is the ground for a need for a second order filter used for renewals team

**Comment by PatrickAGoss** [comment]
Thanks.  I should be a part of that conversation so that Gallagher understands the ask from a Renewals perspective.
