### ISSUE TITLE
Track Down missing $250k Renenue in Renewal Report

### ISSUE THREAD

**Issue by coreywebber** [coreywebber/bdw#96]
This is likely a instance of revenue that is not being captured do to missing status. 

Pat Writes: 
Hi Corey, can you please take a peak at this.  When make a manual formula and compare to what the cube is pulling I get the below variance of 243K,  what do you think is going on?  I understand the 4,119,418 pulls from the Auto tab lower pivot and the category subtotals the same tab but top pivot.  Should they not be the same? 

![renewal_missing_revenue](https://user-images.githubusercontent.com/16250060/68446682-0f86a200-01a3-11ea-8cb5-2d1b1ccba868.jpg)

**Comment by coreywebber** [comment]
going to us the archived version in order to see the data how it looked last quarter

"\\boomi.amer.dell.com\reports$\Archive\FY20Q3\RENEWALS_CUBE.xlsm"

**Comment by coreywebber** [comment]
Hey Pat,

So as I look into to this, I am trying to understand the context, but to start, No Action Needed does not mean deals that have “Closed”, but more like deals we can ignore. The Twist is, in quarter, as your team is booking deals, these status’s are flipping back to No Action Needed, since they have a new subscription end date is not in the future for the account. 

One rabbit hole here is renewals booked early, can make a opportunity with an ending date in future quarter, show no action needed, since the renewal has been booked already.

But the math SUM(All No Action Needed) minus Closed not meaningful or related (directly). 

Not sure if this helps, set up a call with me if I missed the mark here.

**Comment by PatrickAGoss** [comment]
Closed, is it fixed?

**Comment by coreywebber** [comment]
No Action Needed <> Closed, these are not directly related, there is nothing to fix.
